GET http://localhost:3001/api/persons
###
GET http://localhost:3001/api/persons/68cab5579c44f64ed16066e4
###
# DELETE REQ WITH EXISTING AND VALID ID
DELETE http://localhost:3001/api/persons/68cab5579c44f64ed16066e4
# DELETE REQ WITH NON EXISTING BUT VALID ID
DELETE http://localhost:3001/api/persons/68cab5579c44f64ed16066e3
###
POST http://localhost:3001/api/persons
Content-Type: application/json

{
    "name": "Juje",
    "number": "3534694201"
}
###
# PUT http://localhost:3001/api/persons/1
# Content-Type: application/json