POST http://localhost:3001/api/blogs
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Imd1aWRvUyIsImlkIjoiNjhlYTYxZmY2ZDc5NDY0YTBiYmQwYzZhIiwiaWF0IjoxNzYwMzYzMDE1fQ.B_zLgcJG8lUizcfwZlgW3n6AexJvOZgMN7UCmtC9osI

{
  "title": "Cómo usar HTTP en tus proyectos",
  "author": "Guido",
  "url": "https://mi-blog.com/como-usar-http",
  "likes": 10
}
###

POST http://localhost:3001/api/blogs
Content-Type: application/json

{
  "title": "Introducción a REST",
  "author": "Ana",
  "url": "https://mi-blog.com/introduccion-rest",
  "likes": 5
}

###

POST http://localhost:3001/api/blogs
Content-Type: application/json

{
  "title": "Mejores prácticas en APIs",
  "author": "Luis",
  "url": "https://mi-blog.com/mejores-practicas-apis",
  "likes": 20
}